### ISSUE TITLE
Quizz md passt nicht zum Dokument

### ISSUE THREAD

**Issue by tobilektri** [mgudemann/liascriptCourses#5]
Wenn ich die Seite aufrufe (mit Strg+F5 für Cache-invalidate):
https://liascript.github.io/course/?https://api.allorigins.win/raw?url=http://mgu.cs.hm.edu/liascript/krypto.md#1

![image](https://user-images.githubusercontent.com/17339632/150198361-26b839ef-1f5e-4b46-a3ab-7f276c983fcb.png)

--> Alter Stand

https://api.allorigins.win/raw?url=http://mgu.cs.hm.edu/liascript/krypto.md

![image](https://user-images.githubusercontent.com/17339632/150198430-2ead9780-1bd5-4d8c-a8ce-0d34b75206bf.png)
--> Neuer Stand

Woher die Differenz (auch mit anderen Browsern) kommt, weiß ich irgendwie nicht. Ist das nur bei mir so?

**Comment by mgudemann** [comment]
ich habe jetzt mal die Version in der Datei geändert, vllt. cached Liascript dann nicht mehr
Es würde mich freuen, wenn Sie das nochmals kurz ausprobieren könnten

**Comment by tobilektri** [comment]
Funktioniert bei mir leider immer noch nicht... Ich hab aber wirklich auch keine Idee warum....

**Comment by tobilektri** [comment]
Es funktioniert, wenn man an die URL einen Parameter anhängt. Also irgendwo muss ein caching stattfinden, ich verstehe nur nicht wo.

Funktionierendes Beispiel; https://liascript.github.io/course/?https://api.allorigins.win/raw?url=http://mgu.cs.hm.edu/liascript/krypto.md?v=2#11

**Comment by mgudemann** [comment]
sollte passen. Lokales Browser caching ist hier das Problem
