### ISSUE TITLE
Antwortmöglichkeiten zu TI II - DNF verwirrend

### ISSUE THREAD

**Issue by mzinsmeister** [mgudemann/liascriptCourses#7]
Bei der Frage zur DNF in Theoretische Informatik II kann man mehrere Antwortmöglichkeiten auswählen. Trotzdem gibt es die Antwortmöglichkeiten "alle" und "keine". Ich finde das ein wenig verwirrend, da es ja automatisch alle sind wenn man alle auswählt und automatisch keine wenn man keine auswählt. Daher wäre es meiner Ansicht nach besser, diese zwei Antwortmöglichkeiten ganz zu entfernen.

**Comment by mgudemann** [comment]
Ja das stimmt wohl. Das ist der Tatsache geschuldet dass die Fragen 1:1 von BBB übernommen sind und es da ja keine Mehrfachantworten gibt.

**Comment by mzinsmeister** [comment]
> es da ja keine Mehrfachantworten gibt.

NOCH nicht 😉... Der Pull Request ist inzwischen einige Zeit gemerged und dementsprechend sollte es in der 2.5 enthalten sein die vermutlich dieses Jahr irgendwann released wird. Also gut möglich dass es bis zum nächsten Mal TI II schon geht.

**Comment by mgudemann** [comment]
ok, ich korrigiere: ... *noch* keine Mehrfachantworten gibt. :-)
Hier habe ich einfach das Markdown der Folien direkt übernommen. Das werde ich noch ändern

**Comment by mgudemann** [comment]
ist jetzt angepasst. Eventuell durch lokales Browser Caching nicht direkt überall sichtbar.
